stages:
  - deploy

run_test_container:
  stage: deploy
  environment:
    name: test
    url: http://test.elastic.nglm.rt.ru
  before_script:
    - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo podman stop $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE|| echo "Container doesn't started"
    - sudo podman stop $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE|| echo "Container doesn't started"
    - sudo podman rm $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE|| echo "Container doesn't started"
    - sudo podman rm $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE|| echo "Container doesn't started"
    - sudo podman rmi $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest || echo "Image doesn't exist"
    - sudo podman rmi $CI_REGISTRY_IMAGE/$KIBANA_IMAG:latest || echo "Image doesn't exist"
    - sudo podman pull $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest
    - sudo podman pull $CI_REGISTRY_IMAGE/$KIBANA_IMAGE:latest
    - sudo podman pod rm $POD_NAME
  script:
    - sudo podman pod create --name $POD_NAME -p $PORT_EL:9200 -p $PORT_PM:9600 -p $PORT_KIBANA:5601"
    - sudo podman run --env-file=$ELASTIC_ENV_FILE -d --pod $POD_NAME --name $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest
    - sudo podman run -d --pod $POD_NAME --name $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE $CI_REGISTRY_IMAGE/$KIBANA_IMAGE:latest
    - sudo rm /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo cp /config/nginx.config /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo echo "s/#ENVIRONMENT/$CI_ENVIRONMENT_NAME/g" > commands.sed
    - sudo echo "s/#PORT_KIBANA/$PORT_KIBANA/g" >> commands.sed
    - sudo sed -i -f commands.sed /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo systemctl restart nginx

  after_script:
    - date
  except:
    changes:
      - .gitlab-ci.yml
  only:
    - master

run_prod_container:
  stage: deploy
  when:
  environment:
    name: prod
    url: http://prod.elastic.nglm.rt.ru
  before_script:
    - sudo podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - sudo podman stop $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE|| echo "Container doesn't started"
    - sudo podman stop $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE|| echo "Container doesn't started"
    - sudo podman rm $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE|| echo "Container doesn't started"
    - sudo podman rm $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE|| echo "Container doesn't started"
    - sudo podman rmi $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest || echo "Image doesn't exist"
    - sudo podman rmi $CI_REGISTRY_IMAGE/$KIBANA_IMAG:latest || echo "Image doesn't exist"
    - sudo podman pull $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest
    - sudo podman pull $CI_REGISTRY_IMAGE/$KIBANA_IMAGE:latest
    - sudo podman pod rm $POD_NAME
  script:
    - sudo podman pod create --name $POD_NAME -p $PORT_EL:9200 -p $PORT_PM:9600 -p $PORT_KIBANA:5601"
    - sudo podman run --env-file=$ELASTIC_ENV_FILE -d --pod $POD_NAME --name $CI_ENVIRONMENT_NAME-$ELASTIC_IMAGE $CI_REGISTRY_IMAGE/$ELASTIC_IMAGE:latest
    - sudo podman run -d --pod $POD_NAME --name $CI_ENVIRONMENT_NAME-$KIBANA_IMAGE $CI_REGISTRY_IMAGE/$KIBANA_IMAGE:latest
    - sudo rm /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo cp /config/nginx.config /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo echo "s/#ENVIRONMENT/$CI_ENVIRONMENT_NAME/g" > commands.sed
    - sudo echo "s/#PORT_KIBANA/$PORT_KIBANA/g" >> commands.sed
    - sudo sed -i -f commands.sed /etc/nginx/conf.d/$CI_ENVIRONMENT_NAME.elastic.nglm.rt.ru
    - sudo systemctl restart nginx
  after_script:
    - date
  except:
    changes:
      - .gitlab-ci.yml
  only:
    - master
