FROM registry.gitlab.nglm.rt.ru/wombat/elastic-single-instance/opendistro-for-elasticsearch:latest
ENV DOCKERFILE='elastic'
ENV discovery.type=single-node
ENV bootstrap.memory_lock=true
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
